[core]
reloadable = true
order = 0

[package]
version = "0.2.0"
category = "Other"
feature = false
app = false
title = "Data Visualizer (Plots and Images)"
description = "Switch Matplotlib and OpenCV backend to display graphics and images inside NVIDIA Omniverse apps"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/semu.data.visualizer"
keywords = ["data", "image", "plot"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[package.target]
config = ["release"]
platform = ["linux-*", "windows-*"]
python = ["*"]

[dependencies]
"omni.ui" = {}
"omni.kit.uiapp" = {}
"omni.kit.pipapi" = {}

[python.pipapi]
requirements = ["numpy", "matplotlib", "opencv-python"]

[[python.module]]
name = "semu.data.visualizer"

[[python.module]]
name = "semu.data.visualizer.tests"

[settings]
exts."semu.data.visualizer".default_matplotlib_backend_if_agg = "Agg"
