[core]
reloadable = true
order = 0

[package]
version = "0.0.2"
category = "Other"
title = "Data Visualizer (Plots and Images)"
description = "Data visualization with Matplotlib and OpenCV-like interfaces and native Omniverse plots"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/omni.add_on.visualizer"
keywords = ["data", "image", "plot"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.ui" = {}
"omni.kit.uiapp" = {}
"omni.kit.pip_archive" = {} # pulls in numpy and matplotlib

[[python.module]]
name = "omni.add_on.visualizer"

[[python.module]]
name = "omni.add_on.visualizer.tests"